# Generated by Django 5.2.12 on 2026-06-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_supplierrestockbill_suppliershop_supplierrestockitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpayment',
            name='linked_bill',
        ),
    ]
