# Generated by Django 5.2.9 on 2026-01-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='mileage',
            field=models.CharField(blank=True, help_text='e.g. 50000 or 50k', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
