# Generated by Django 5.2.9 on 2026-01-15 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_jobcard_mileage_alter_jobcard_customer_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcardspareitem',
            name='labour_charge',
        ),
        migrations.CreateModel(
            name='JobCardLabourItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labours', to='workshop.jobcard')),
            ],
        ),
    ]
