# Generated by Django 5.2.9 on 2026-01-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_remove_jobcardspareitem_labour_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardlabouritem',
            name='job_description',
            field=models.CharField(max_length=150),
        ),
    ]
