# Generated by Django 5.2.9 on 2026-01-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_alter_jobcardspareitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardlabouritem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
