# Generated by Django 5.2.9 on 2026-01-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_alter_jobcardlabouritem_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='delivered',
            field=models.BooleanField(default=False, help_text='Actually delivered (marked via Delivered button)'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='discharged_date',
            field=models.DateField(blank=True, help_text='Planning date - when you plan to deliver', null=True),
        ),
    ]
