# Generated by Django 5.2.9 on 2026-01-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_jobcard_delivered_alter_jobcard_discharged_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='bill_number',
            field=models.CharField(blank=True, help_text='Auto-generated bill number (e.g. JB-26-001)', max_length=20, null=True, unique=True),
        ),
    ]
