# Generated by Django 5.2.9 on 2026-01-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_jobcard_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardconcern',
            name='status',
            field=models.CharField(choices=[('HOLD', 'Hold'), ('PROCESSING', 'Processing'), ('FIXED', 'Fixed')], default='HOLD', max_length=20),
        ),
        migrations.AddField(
            model_name='jobcardspareitem',
            name='status',
            field=models.CharField(choices=[('HOLD', 'Hold'), ('ORDERED', 'Ordered'), ('RECEIVED', 'Received')], default='HOLD', max_length=20),
        ),
    ]
