# Generated by Django 5.2.9 on 2026-01-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_jobcardconcern_status_jobcardspareitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardconcern',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WORKING', 'Working'), ('FIXED', 'Fixed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobcardspareitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ORDERED', 'Ordered'), ('FIXED', 'Fixed')], default='PENDING', max_length=20),
        ),
    ]
