# Generated by Django 5.2.9 on 2026-01-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_alter_jobcardconcern_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='on_hold',
            field=models.BooleanField(default=False, help_text='Job is on hold (waiting for parts, etc.)'),
        ),
    ]
