# Generated by Django 5.2.9 on 2026-01-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0011_jobcard_on_hold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='discharged_date',
            field=models.DateField(blank=True, help_text='Auto-filled when job is marked as delivered', null=True),
        ),
        migrations.AlterField(
            model_name='jobcardspareitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ORDERED', 'Ordered'), ('RECEIVED', 'Received')], default='PENDING', max_length=20),
        ),
    ]
