# Generated by Django 5.2.9 on 2026-01-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_alter_jobcard_discharged_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concernsolution',
            name='solution',
            field=models.TextField(blank=True, help_text='e.g., Change brake pads', null=True),
        ),
    ]
