# Generated by Django 5.2.9 on 2026-01-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0013_make_concern_solution_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardspareitem',
            name='ordered_date',
            field=models.DateField(blank=True, help_text='Auto-filled when status → ORDERED', null=True),
        ),
        migrations.AddField(
            model_name='jobcardspareitem',
            name='received_date',
            field=models.DateField(blank=True, help_text='Auto-filled when status → RECEIVED', null=True),
        ),
        migrations.AddField(
            model_name='jobcardspareitem',
            name='shop_name',
            field=models.CharField(blank=True, help_text='Shop where part was ordered', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobcardspareitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Customer price (with markup)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobcardspareitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Shop price (cost)', max_digits=10, null=True),
        ),
    ]
