# Generated by Django 5.2.9 on 2026-03-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0015_mechanic_jobcard_lead_mechanic_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount given to the customer', max_digits=10),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI / QR Code'), ('CARD', 'Credit/Debit Card'), ('TRANSFER', 'Bank Transfer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending (Unpaid)'), ('PAID', 'Fully Paid'), ('PARTIAL', 'Partially Paid')], default='PENDING', max_length=20),
        ),
    ]
