# Generated by Django 5.2.9 on 2026-03-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0016_jobcard_discount_amount_jobcard_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount actually received from customer', max_digits=10),
        ),
    ]
