# Generated by Django 5.2.9 on 2026-03-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0017_remove_jobcard_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Internal discount tracking (calculated on Paid status)', max_digits=10),
        ),
    ]
