# Generated by Django 5.2.9 on 2026-03-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0018_jobcard_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='car_color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Silver', 'Silver'), ('Red', 'Red'), ('Brown', 'Brown'), ('Dark Brown', 'Dark Brown'), ('Blue', 'Blue'), ('Light Blue', 'Light Blue'), ('Dark Blue', 'Dark Blue'), ('Green', 'Green'), ('Light Green', 'Light Green'), ('Dark Green', 'Dark Green'), ('Grey', 'Grey'), ('Yellow', 'Yellow'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='car_color_other',
            field=models.CharField(blank=True, help_text="Specific color name if 'Other' is selected", max_length=100, null=True),
        ),
    ]
