# Generated by Django 5.2.9 on 2026-03-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0019_jobcard_car_color_jobcard_car_color_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concernsolution',
            name='solution',
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='car_color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Silver', 'Silver'), ('Grey', 'Grey'), ('Red', 'Red'), ('Light Blue', 'Light Blue'), ('Blue', 'Blue'), ('Dark Blue', 'Dark Blue'), ('Yellow', 'Yellow'), ('Light Green', 'Light Green'), ('Green', 'Green'), ('Dark Green', 'Dark Green'), ('Brown', 'Brown'), ('Dark Brown', 'Dark Brown'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
