# Generated by Django 5.2.12 on 2026-03-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0020_remove_concernsolution_solution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='sample_image',
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='customer_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='discharged_date',
            field=models.DateField(blank=True, db_index=True, help_text='Auto-filled when job is marked as delivered', null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='registration_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
