# Generated by Django 5.2.12 on 2026-03-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0021_remove_carmodel_sample_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending (Unpaid)'), ('PAID', 'Fully Paid'), ('PARTIAL', 'Partially Paid')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
