# Generated by Django 5.2.12 on 2026-03-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0022_alter_jobcard_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Hide from main list (moved to trash)'),
        ),
    ]
