# Generated by Django 5.2.12 on 2026-03-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0023_jobcard_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='brand_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='model_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
