# Generated by Django 5.2.12 on 2026-04-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0024_alter_jobcard_brand_name_alter_jobcard_model_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcard',
            options={},
        ),
        migrations.AddField(
            model_name='jobcard',
            name='total_bill_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Denormalized total for instant dashboard loading', max_digits=12),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='admitted_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Internal discount tracking (calculated on Paid status)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount actually received from customer', max_digits=12),
        ),
    ]
