# Generated by Django 5.2.12 on 2026-04-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0025_alter_jobcard_options_jobcard_total_bill_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
