# Generated by Django 5.2.12 on 2026-04-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0027_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
