# Generated by Django 5.2.12 on 2026-04-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0029_failedattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcard',
            options={'verbose_name': 'Job Card', 'verbose_name_plural': 'Job Cards'},
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='delivered',
            field=models.BooleanField(db_index=True, default=False, help_text='Actually delivered (marked via Delivered button)'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['is_deleted', 'delivered', '-updated_at'], name='workshop_jo_is_dele_95b87f_idx'),
        ),
    ]
