# Generated by Django 5.2.12 on 2026-05-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0030_alter_jobcard_options_alter_jobcard_delivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending (Unpaid)'), ('PAID', 'Fully Paid'), ('PARTIAL', 'Partially Paid'), ('BULK_PAID', 'Bulk Paid')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='BulkPayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_cards', models.ManyToManyField(blank=True, related_name='bulk_payers', to='workshop.jobcard')),
            ],
            options={
                'ordering': ['customer_name'],
            },
        ),
    ]
