# Generated by Django 5.2.12 on 2026-05-13 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0031_alter_jobcard_payment_status_bulkpayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkpayer',
            name='is_trashed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='BulkPaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('TRANSFER', 'Bank Transfer')], default='CASH', max_length=20)),
                ('jobs_affected', models.PositiveIntegerField(default=0)),
                ('details', models.TextField(blank=True, help_text='JSON snapshot of which jobs got how much')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bulk_payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='workshop.bulkpayer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
