# Generated by Django 5.2.12 on 2026-05-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0032_bulkpayer_is_trashed_bulkpaymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkpaymenthistory',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
