# Generated by Django 5.2.12 on 2026-06-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0036_alter_jobcardspareitem_ordered_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcardspareitem',
            name='shop_paid_amount',
        ),
        migrations.RemoveField(
            model_name='spareshoppayment',
            name='details',
        ),
        migrations.RemoveField(
            model_name='spareshoppayment',
            name='items_affected',
        ),
        migrations.AddField(
            model_name='spareshop',
            name='total_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='spareshop',
            name='total_purchased_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
